[project]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Testing Repo"
name = "mojo-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
temp = "mojo temp/temp.mojo"

[dependencies]
max = "*"
